<?php

// ISO 3166-1 alpha-2 billing countries for Bankart (CG/EN labels)

return [
    'AD' => ['cg' => 'Andora', 'en' => 'Andorra'],
    'AE' => ['cg' => 'Ujedinjeni Arapski Emirati', 'en' => 'United Arab Emirates'],
    'AF' => ['cg' => 'Afganistan', 'en' => 'Afghanistan'],
    'AG' => ['cg' => 'Antigva i Barbuda', 'en' => 'Antigua and Barbuda'],
    'AI' => ['cg' => 'Angvila', 'en' => 'Anguilla'],
    'AL' => ['cg' => 'Albanija', 'en' => 'Albania'],
    'AM' => ['cg' => 'Jermenija', 'en' => 'Armenia'],
    'AO' => ['cg' => 'Angola', 'en' => 'Angola'],
    'AQ' => ['cg' => 'Antarktik', 'en' => 'Antarctica'],
    'AR' => ['cg' => 'Argentina', 'en' => 'Argentina'],
    'AS' => ['cg' => 'Američka Samoa', 'en' => 'American Samoa'],
    'AT' => ['cg' => 'Austrija', 'en' => 'Austria'],
    'AU' => ['cg' => 'Australija', 'en' => 'Australia'],
    'AW' => ['cg' => 'Aruba', 'en' => 'Aruba'],
    'AX' => ['cg' => 'Olandska ostrva', 'en' => 'Åland Islands'],
    'AZ' => ['cg' => 'Azerbejdžan', 'en' => 'Azerbaijan'],
    'BA' => ['cg' => 'Bosna i Hercegovina', 'en' => 'Bosnia and Herzegovina'],
    'BB' => ['cg' => 'Barbados', 'en' => 'Barbados'],
    'BD' => ['cg' => 'Bangladeš', 'en' => 'Bangladesh'],
    'BE' => ['cg' => 'Belgija', 'en' => 'Belgium'],
    'BF' => ['cg' => 'Burkina Faso', 'en' => 'Burkina Faso'],
    'BG' => ['cg' => 'Bugarska', 'en' => 'Bulgaria'],
    'BH' => ['cg' => 'Bahrein', 'en' => 'Bahrain'],
    'BI' => ['cg' => 'Burundi', 'en' => 'Burundi'],
    'BJ' => ['cg' => 'Benin', 'en' => 'Benin'],
    'BL' => ['cg' => 'Sveti Bartolomej', 'en' => 'Saint Barthélemy'],
    'BM' => ['cg' => 'Bermudi', 'en' => 'Bermuda'],
    'BN' => ['cg' => 'Brunej', 'en' => 'Brunei Darussalam'],
    'BO' => ['cg' => 'Bolivija', 'en' => 'Bolivia'],
    'BQ' => ['cg' => 'Bonaire, Sint Eustasius i Saba', 'en' => 'Bonaire, Sint Eustatius and Saba'],
    'BR' => ['cg' => 'Brazil', 'en' => 'Brazil'],
    'BS' => ['cg' => 'Bahami', 'en' => 'Bahamas'],
    'BT' => ['cg' => 'Butan', 'en' => 'Bhutan'],
    'BV' => ['cg' => 'Buve', 'en' => 'Bouvet Island'],
    'BW' => ['cg' => 'Bocvana', 'en' => 'Botswana'],
    'BY' => ['cg' => 'Bjelorusija', 'en' => 'Belarus'],
    'BZ' => ['cg' => 'Belize', 'en' => 'Belize'],
    'CA' => ['cg' => 'Kanada', 'en' => 'Canada'],
    'CC' => ['cg' => 'Kokosova ostrva', 'en' => 'Cocos (Keeling) Islands'],
    'CD' => ['cg' => 'Demokratska Republika Kongo', 'en' => 'Congo, Democratic Republic of the'],
    'CF' => ['cg' => 'Centralnoafrička Republika', 'en' => 'Central African Republic'],
    'CG' => ['cg' => 'Kongo', 'en' => 'Congo'],
    'CH' => ['cg' => 'Švajcarska', 'en' => 'Switzerland'],
    'CI' => ['cg' => 'Obala Slonovače', 'en' => 'Côte d\'Ivoire'],
    'CK' => ['cg' => 'Kukova ostrva', 'en' => 'Cook Islands'],
    'CL' => ['cg' => 'Čile', 'en' => 'Chile'],
    'CM' => ['cg' => 'Kamerun', 'en' => 'Cameroon'],
    'CN' => ['cg' => 'Kina', 'en' => 'China'],
    'CO' => ['cg' => 'Kolumbija', 'en' => 'Colombia'],
    'CR' => ['cg' => 'Kostarika', 'en' => 'Costa Rica'],
    'CU' => ['cg' => 'Kuba', 'en' => 'Cuba'],
    'CV' => ['cg' => 'Zelenortska Ostrva', 'en' => 'Cabo Verde'],
    'CW' => ['cg' => 'Kurasao', 'en' => 'Curaçao'],
    'CX' => ['cg' => 'Božićno ostrvo', 'en' => 'Christmas Island'],
    'CY' => ['cg' => 'Kipar', 'en' => 'Cyprus'],
    'CZ' => ['cg' => 'Češka', 'en' => 'Czechia'],
    'DE' => ['cg' => 'Njemačka', 'en' => 'Germany'],
    'DJ' => ['cg' => 'Džibuti', 'en' => 'Djibouti'],
    'DK' => ['cg' => 'Danska', 'en' => 'Denmark'],
    'DM' => ['cg' => 'Dominika', 'en' => 'Dominica'],
    'DO' => ['cg' => 'Dominikanska Republika', 'en' => 'Dominican Republic'],
    'DZ' => ['cg' => 'Alžir', 'en' => 'Algeria'],
    'EC' => ['cg' => 'Ekvador', 'en' => 'Ecuador'],
    'EE' => ['cg' => 'Estonija', 'en' => 'Estonia'],
    'EG' => ['cg' => 'Egipat', 'en' => 'Egypt'],
    'EH' => ['cg' => 'Zapadna Sahara', 'en' => 'Western Sahara'],
    'ER' => ['cg' => 'Eritreja', 'en' => 'Eritrea'],
    'ES' => ['cg' => 'Španija', 'en' => 'Spain'],
    'ET' => ['cg' => 'Etiopija', 'en' => 'Ethiopia'],
    'FI' => ['cg' => 'Finska', 'en' => 'Finland'],
    'FJ' => ['cg' => 'Fidži', 'en' => 'Fiji'],
    'FK' => ['cg' => 'Falklandska ostrva', 'en' => 'Falkland Islands'],
    'FM' => ['cg' => 'Mikronezija', 'en' => 'Micronesia'],
    'FO' => ['cg' => 'Farska ostrva', 'en' => 'Faroe Islands'],
    'FR' => ['cg' => 'Francuska', 'en' => 'France'],
    'GA' => ['cg' => 'Gabon', 'en' => 'Gabon'],
    'GB' => ['cg' => 'Ujedinjeno Kraljevstvo', 'en' => 'United Kingdom'],
    'GD' => ['cg' => 'Grenada', 'en' => 'Grenada'],
    'GE' => ['cg' => 'Gruzija', 'en' => 'Georgia'],
    'GF' => ['cg' => 'Francuska Gvajana', 'en' => 'French Guiana'],
    'GG' => ['cg' => 'Gernzi', 'en' => 'Guernsey'],
    'GH' => ['cg' => 'Gana', 'en' => 'Ghana'],
    'GI' => ['cg' => 'Gibraltar', 'en' => 'Gibraltar'],
    'GL' => ['cg' => 'Grenland', 'en' => 'Greenland'],
    'GM' => ['cg' => 'Gambija', 'en' => 'Gambia'],
    'GN' => ['cg' => 'Gvineja', 'en' => 'Guinea'],
    'GP' => ['cg' => 'Gvadelup', 'en' => 'Guadeloupe'],
    'GQ' => ['cg' => 'Ekvatorijalna Gvineja', 'en' => 'Equatorial Guinea'],
    'GR' => ['cg' => 'Grčka', 'en' => 'Greece'],
    'GS' => ['cg' => 'Južna Džordžija i Južna Sendvič ostrva', 'en' => 'South Georgia and the South Sandwich Islands'],
    'GT' => ['cg' => 'Gvatemala', 'en' => 'Guatemala'],
    'GU' => ['cg' => 'Guam', 'en' => 'Guam'],
    'GW' => ['cg' => 'Gvineja Bisao', 'en' => 'Guinea-Bissau'],
    'GY' => ['cg' => 'Gvajana', 'en' => 'Guyana'],
    'HK' => ['cg' => 'Hong Kong', 'en' => 'Hong Kong'],
    'HM' => ['cg' => 'Ostrvo Herd i ostrva Makdonald', 'en' => 'Heard Island and McDonald Islands'],
    'HN' => ['cg' => 'Honduras', 'en' => 'Honduras'],
    'HR' => ['cg' => 'Hrvatska', 'en' => 'Croatia'],
    'HT' => ['cg' => 'Haiti', 'en' => 'Haiti'],
    'HU' => ['cg' => 'Mađarska', 'en' => 'Hungary'],
    'ID' => ['cg' => 'Indonezija', 'en' => 'Indonesia'],
    'IE' => ['cg' => 'Irska', 'en' => 'Ireland'],
    'IL' => ['cg' => 'Izrael', 'en' => 'Israel'],
    'IM' => ['cg' => 'Ostrvo Man', 'en' => 'Isle of Man'],
    'IN' => ['cg' => 'Indija', 'en' => 'India'],
    'IO' => ['cg' => 'Britanska teritorija Indijskog okeana', 'en' => 'British Indian Ocean Territory'],
    'IQ' => ['cg' => 'Irak', 'en' => 'Iraq'],
    'IR' => ['cg' => 'Iran', 'en' => 'Iran'],
    'IS' => ['cg' => 'Island', 'en' => 'Iceland'],
    'IT' => ['cg' => 'Italija', 'en' => 'Italy'],
    'JE' => ['cg' => 'Džerzi', 'en' => 'Jersey'],
    'JM' => ['cg' => 'Jamajka', 'en' => 'Jamaica'],
    'JO' => ['cg' => 'Jordan', 'en' => 'Jordan'],
    'JP' => ['cg' => 'Japan', 'en' => 'Japan'],
    'KE' => ['cg' => 'Kenija', 'en' => 'Kenya'],
    'KG' => ['cg' => 'Kirgistan', 'en' => 'Kyrgyzstan'],
    'KH' => ['cg' => 'Kambodža', 'en' => 'Cambodia'],
    'KI' => ['cg' => 'Kiribati', 'en' => 'Kiribati'],
    'KM' => ['cg' => 'Komori', 'en' => 'Comoros'],
    'KN' => ['cg' => 'Sveti Kits i Nevis', 'en' => 'Saint Kitts and Nevis'],
    'KP' => ['cg' => 'Sjeverna Koreja', 'en' => 'Korea, Democratic People\'s Republic of'],
    'KR' => ['cg' => 'Južna Koreja', 'en' => 'Korea, Republic of'],
    'KW' => ['cg' => 'Kuvajt', 'en' => 'Kuwait'],
    'KY' => ['cg' => 'Kajmanska ostrva', 'en' => 'Cayman Islands'],
    'KZ' => ['cg' => 'Kazahstan', 'en' => 'Kazakhstan'],
    'LA' => ['cg' => 'Laos', 'en' => 'Lao People\'s Democratic Republic'],
    'LB' => ['cg' => 'Liban', 'en' => 'Lebanon'],
    'LC' => ['cg' => 'Sveta Lucija', 'en' => 'Saint Lucia'],
    'LI' => ['cg' => 'Lihtenštajn', 'en' => 'Liechtenstein'],
    'LK' => ['cg' => 'Šri Lanka', 'en' => 'Sri Lanka'],
    'LR' => ['cg' => 'Liberija', 'en' => 'Liberia'],
    'LS' => ['cg' => 'Lesoto', 'en' => 'Lesotho'],
    'LT' => ['cg' => 'Litvanija', 'en' => 'Lithuania'],
    'LU' => ['cg' => 'Luksemburg', 'en' => 'Luxembourg'],
    'LV' => ['cg' => 'Letonija', 'en' => 'Latvia'],
    'LY' => ['cg' => 'Libija', 'en' => 'Libya'],
    'MA' => ['cg' => 'Maroko', 'en' => 'Morocco'],
    'MC' => ['cg' => 'Monako', 'en' => 'Monaco'],
    'MD' => ['cg' => 'Moldavija', 'en' => 'Moldova'],
    'ME' => ['cg' => 'Crna Gora', 'en' => 'Montenegro'],
    'MF' => ['cg' => 'Sveti Martin (francuski deo)', 'en' => 'Saint Martin (French part)'],
    'MG' => ['cg' => 'Madagaskar', 'en' => 'Madagascar'],
    'MH' => ['cg' => 'Maršalska ostrva', 'en' => 'Marshall Islands'],
    'MK' => ['cg' => 'Sjeverna Makedonija', 'en' => 'North Macedonia'],
    'ML' => ['cg' => 'Mali', 'en' => 'Mali'],
    'MM' => ['cg' => 'Mijanmar', 'en' => 'Myanmar'],
    'MN' => ['cg' => 'Mongolija', 'en' => 'Mongolia'],
    'MO' => ['cg' => 'Makao', 'en' => 'Macao'],
    'MP' => ['cg' => 'Sjeverna Marijanska ostrva', 'en' => 'Northern Mariana Islands'],
    'MQ' => ['cg' => 'Martinik', 'en' => 'Martinique'],
    'MR' => ['cg' => 'Mauritanija', 'en' => 'Mauritania'],
    'MS' => ['cg' => 'Monserat', 'en' => 'Montserrat'],
    'MT' => ['cg' => 'Malta', 'en' => 'Malta'],
    'MU' => ['cg' => 'Mauricijus', 'en' => 'Mauritius'],
    'MV' => ['cg' => 'Maldivi', 'en' => 'Maldives'],
    'MW' => ['cg' => 'Malavi', 'en' => 'Malawi'],
    'MX' => ['cg' => 'Meksiko', 'en' => 'Mexico'],
    'MY' => ['cg' => 'Malezija', 'en' => 'Malaysia'],
    'MZ' => ['cg' => 'Mozambik', 'en' => 'Mozambique'],
    'NA' => ['cg' => 'Namibija', 'en' => 'Namibia'],
    'NC' => ['cg' => 'Nova Kaledonija', 'en' => 'New Caledonia'],
    'NE' => ['cg' => 'Niger', 'en' => 'Niger'],
    'NF' => ['cg' => 'Ostrvo Norfolk', 'en' => 'Norfolk Island'],
    'NG' => ['cg' => 'Nigerija', 'en' => 'Nigeria'],
    'NI' => ['cg' => 'Nikaragva', 'en' => 'Nicaragua'],
    'NL' => ['cg' => 'Holandija', 'en' => 'Netherlands'],
    'NO' => ['cg' => 'Norveška', 'en' => 'Norway'],
    'NP' => ['cg' => 'Nepal', 'en' => 'Nepal'],
    'NR' => ['cg' => 'Nauru', 'en' => 'Nauru'],
    'NU' => ['cg' => 'Niue', 'en' => 'Niue'],
    'NZ' => ['cg' => 'Novi Zeland', 'en' => 'New Zealand'],
    'OM' => ['cg' => 'Oman', 'en' => 'Oman'],
    'PA' => ['cg' => 'Panama', 'en' => 'Panama'],
    'PE' => ['cg' => 'Peru', 'en' => 'Peru'],
    'PF' => ['cg' => 'Francuska Polinezija', 'en' => 'French Polynesia'],
    'PG' => ['cg' => 'Papua Nova Gvineja', 'en' => 'Papua New Guinea'],
    'PH' => ['cg' => 'Filipini', 'en' => 'Philippines'],
    'PK' => ['cg' => 'Pakistan', 'en' => 'Pakistan'],
    'PL' => ['cg' => 'Poljska', 'en' => 'Poland'],
    'PM' => ['cg' => 'Sveti Pjer i Mikelon', 'en' => 'Saint Pierre and Miquelon'],
    'PN' => ['cg' => 'Pitkern', 'en' => 'Pitcairn'],
    'PR' => ['cg' => 'Portoriko', 'en' => 'Puerto Rico'],
    'PS' => ['cg' => 'Palestina', 'en' => 'Palestine, State of'],
    'PT' => ['cg' => 'Portugal', 'en' => 'Portugal'],
    'PW' => ['cg' => 'Palau', 'en' => 'Palau'],
    'PY' => ['cg' => 'Paragvaj', 'en' => 'Paraguay'],
    'QA' => ['cg' => 'Katar', 'en' => 'Qatar'],
    'RE' => ['cg' => 'Reunion', 'en' => 'Réunion'],
    'RO' => ['cg' => 'Rumunija', 'en' => 'Romania'],
    'RS' => ['cg' => 'Srbija', 'en' => 'Serbia'],
    'RU' => ['cg' => 'Rusija', 'en' => 'Russian Federation'],
    'RW' => ['cg' => 'Ruanda', 'en' => 'Rwanda'],
    'SA' => ['cg' => 'Saudijska Arabija', 'en' => 'Saudi Arabia'],
    'SB' => ['cg' => 'Solomonova ostrva', 'en' => 'Solomon Islands'],
    'SC' => ['cg' => 'Sejšeli', 'en' => 'Seychelles'],
    'SD' => ['cg' => 'Sudan', 'en' => 'Sudan'],
    'SE' => ['cg' => 'Švedska', 'en' => 'Sweden'],
    'SG' => ['cg' => 'Singapur', 'en' => 'Singapore'],
    'SH' => ['cg' => 'Sveta Helena', 'en' => 'Saint Helena, Ascension and Tristan da Cunha'],
    'SI' => ['cg' => 'Slovenija', 'en' => 'Slovenia'],
    'SJ' => ['cg' => 'Svalbard i Jan Majen', 'en' => 'Svalbard and Jan Mayen'],
    'SK' => ['cg' => 'Slovačka', 'en' => 'Slovakia'],
    'SL' => ['cg' => 'Sijera Leone', 'en' => 'Sierra Leone'],
    'SM' => ['cg' => 'San Marino', 'en' => 'San Marino'],
    'SN' => ['cg' => 'Senegal', 'en' => 'Senegal'],
    'SO' => ['cg' => 'Somalija', 'en' => 'Somalia'],
    'SR' => ['cg' => 'Surinam', 'en' => 'Suriname'],
    'SS' => ['cg' => 'Južni Sudan', 'en' => 'South Sudan'],
    'ST' => ['cg' => 'Sao Tome i Principe', 'en' => 'Sao Tome and Principe'],
    'SV' => ['cg' => 'Salvador', 'en' => 'El Salvador'],
    'SX' => ['cg' => 'Sint Marten', 'en' => 'Sint Maarten (Dutch part)'],
    'SY' => ['cg' => 'Sirija', 'en' => 'Syrian Arab Republic'],
    'SZ' => ['cg' => 'Esvatini', 'en' => 'Eswatini'],
    'TC' => ['cg' => 'Ostrva Turks i Kaikos', 'en' => 'Turks and Caicos Islands'],
    'TD' => ['cg' => 'Čad', 'en' => 'Chad'],
    'TF' => ['cg' => 'Francuske južne teritorije', 'en' => 'French Southern Territories'],
    'TG' => ['cg' => 'Togo', 'en' => 'Togo'],
    'TH' => ['cg' => 'Tajland', 'en' => 'Thailand'],
    'TJ' => ['cg' => 'Tadžikistan', 'en' => 'Tajikistan'],
    'TK' => ['cg' => 'Tokelau', 'en' => 'Tokelau'],
    'TL' => ['cg' => 'Istočni Timor', 'en' => 'Timor-Leste'],
    'TM' => ['cg' => 'Turkmenistan', 'en' => 'Turkmenistan'],
    'TN' => ['cg' => 'Tunis', 'en' => 'Tunisia'],
    'TO' => ['cg' => 'Tonga', 'en' => 'Tonga'],
    'TR' => ['cg' => 'Turska', 'en' => 'Turkey'],
    'TT' => ['cg' => 'Trinidad i Tobago', 'en' => 'Trinidad and Tobago'],
    'TV' => ['cg' => 'Tuvalu', 'en' => 'Tuvalu'],
    'TW' => ['cg' => 'Tajvan', 'en' => 'Taiwan'],
    'TZ' => ['cg' => 'Tanzanija', 'en' => 'Tanzania, United Republic of'],
    'UA' => ['cg' => 'Ukrajina', 'en' => 'Ukraine'],
    'UG' => ['cg' => 'Uganda', 'en' => 'Uganda'],
    'UM' => ['cg' => 'Mala udaljena ostrva SAD', 'en' => 'United States Minor Outlying Islands'],
    'US' => ['cg' => 'Sjedinjene Američke Države', 'en' => 'United States of America'],
    'UY' => ['cg' => 'Urugvaj', 'en' => 'Uruguay'],
    'UZ' => ['cg' => 'Uzbekistan', 'en' => 'Uzbekistan'],
    'VA' => ['cg' => 'Vatikan', 'en' => 'Holy See'],
    'VC' => ['cg' => 'Sveti Vinsent i Grenadini', 'en' => 'Saint Vincent and the Grenadines'],
    'VE' => ['cg' => 'Venecuela', 'en' => 'Venezuela'],
    'VG' => ['cg' => 'Britanska Djevičanska ostrva', 'en' => 'Virgin Islands (British)'],
    'VI' => ['cg' => 'Američka Djevičanska ostrva', 'en' => 'Virgin Islands (U.S.)'],
    'VN' => ['cg' => 'Vijetnam', 'en' => 'Viet Nam'],
    'VU' => ['cg' => 'Vanuatu', 'en' => 'Vanuatu'],
    'WF' => ['cg' => 'Valis i Futuna', 'en' => 'Wallis and Futuna'],
    'WS' => ['cg' => 'Samoa', 'en' => 'Samoa'],
    'XK' => ['cg' => 'Kosovo', 'en' => 'Kosovo'],
    'YE' => ['cg' => 'Jemen', 'en' => 'Yemen'],
    'YT' => ['cg' => 'Majot', 'en' => 'Mayotte'],
    'ZA' => ['cg' => 'Južnoafrička Republika', 'en' => 'South Africa'],
    'ZM' => ['cg' => 'Zambija', 'en' => 'Zambia'],
    'ZW' => ['cg' => 'Zimbabve', 'en' => 'Zimbabwe'],
];
